<a href="https://colab.research.google.com/github/anuradha-datascience/NLP/blob/main/HandsOnNLPWithConcept_Part3__Preprocess_TFIDFUsingsklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
import pandas as pd
import chardet
with open('SMSSpamCollection.csv', 'rb') as f:
    encoding = chardet.detect(f.read())['encoding']


In [116]:
df=pd.read_csv('SMSSpamCollection.csv',sep="\t",names=["label","message"],encoding=encoding)

In [117]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [118]:
df.shape

(5572, 2)

In [119]:
df['message'].loc[100]

"Please don't text me anymore. I have nothing else to say."


**Data Cleaning and Preprocessing**


1.   Text Preprocessing
  *   Tokenization
  *   Stop Words
  *   Stemming
  *   POS Tagging
  *   Lemmetization
  *   NLTK Library

2.   Word Embeddings

Frequency-based Embedding
  *   BOW
  *   TFIDF
  *   Glove

Prediction-based Embedding
  *   Word2Vec
  *   AvgWord2Vec
  *   BERT






In [120]:

import nltk
import string
#download resources
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [121]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


In [122]:
#tokenize text
df["message_preprocess"]=df['message'].apply(lambda x: word_tokenize(x))
df["message_preprocess"].head()

0    [Go, until, jurong, point, ,, crazy, .., Avail...
1             [Ok, lar, ..., Joking, wif, u, oni, ...]
2    [Free, entry, in, 2, a, wkly, comp, to, win, F...
3    [U, dun, say, so, early, hor, ..., U, c, alrea...
4    [Nah, I, do, n't, think, he, goes, to, usf, ,,...
Name: message_preprocess, dtype: object

In [123]:
df["message_preprocess"].loc[100]



['Please',
 'do',
 "n't",
 'text',
 'me',
 'anymore',
 '.',
 'I',
 'have',
 'nothing',
 'else',
 'to',
 'say',
 '.']

In [124]:
# Get the English stopwords list
stopwords_list = stopwords.words('english')

# Print the stopwords list
print(stopwords_list)

print(string.punctuation)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [125]:
# remove punctuations and stop words
stop_words = stopwords.words('english') + list(string.punctuation)


In [126]:
#word lowering , stop word and punctuation removal, number removal
def filter_tokens(tokens):
    filtered_tokens = [word.lower() for word in tokens if word.lower() not in stop_words]
    filtered_tokens=[token for token in filtered_tokens if token.isalpha()]
    return filtered_tokens

In [127]:
df["message_preprocess"]=df['message_preprocess'].apply(lambda x: filter_tokens(x))
df["message_preprocess"].head()

0    [go, jurong, point, crazy, available, bugis, n...
1                       [ok, lar, joking, wif, u, oni]
2    [free, entry, wkly, comp, win, fa, cup, final,...
3        [u, dun, say, early, hor, u, c, already, say]
4       [nah, think, goes, usf, lives, around, though]
Name: message_preprocess, dtype: object

In [128]:
df["message_preprocess"].loc[1100]

['ne',
 'thing',
 'interesting',
 'good',
 'birthday',
 'u',
 'wrking',
 'nxt',
 'started',
 'uni',
 'today']

In [129]:
#stemming vs lemmatization
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()
def stemming(tokens):

  tokens = [stemmer.stem(token) for token in tokens]
  return tokens

In [130]:
# df["message_preprocess_new"]=df['message_preprocess'].apply(lambda x: stemming(x))
# df["message_preprocess_new"].head()

In [131]:
tokens =["ok", "lar", "jokinging", "wif", "u", "oni","joining"]
new=stemming(tokens)
print(new)

['ok', 'lar', 'joking', 'wif', 'u', 'oni', 'join']


In [132]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

def get_wordnet_pos(word):
    """Map POS tag to first character lemmatize() accepts"""
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

def lemmatization(tokens):
    # Lemmatization with POS tagging
    lemmatizer = WordNetLemmatizer()
    lem_tokens = [lemmatizer.lemmatize(token, get_wordnet_pos(token)) for token in tokens]
    return lem_tokens

# Example usage
tokens = ["running", "cars", "swimming"]
lemmatized_tokens = lemmatization(tokens)
print(lemmatized_tokens)

['run', 'car', 'swim']


[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [133]:
df["message_preprocess"]=df['message_preprocess'].apply(lambda x: stemming(x))
df["message_preprocess"].head()

0    [go, jurong, point, crazi, avail, bugi, n, gre...
1                         [ok, lar, joke, wif, u, oni]
2    [free, entri, wkli, comp, win, fa, cup, final,...
3        [u, dun, say, earli, hor, u, c, alreadi, say]
4         [nah, think, goe, usf, live, around, though]
Name: message_preprocess, dtype: object

In [134]:
# let's make a single function for preprocessing using nltk
def get_wordnet_pos(word):
  """Map POS tag to first character lemmatize() accepts"""
  tag = nltk.pos_tag([word])[0][1][0].upper()
  tag_dict = {"J": wordnet.ADJ,
              "N": wordnet.NOUN,
              "V": wordnet.VERB,
              "R": wordnet.ADV}
  return tag_dict.get(tag, wordnet.NOUN)

def preprocess_data(text):
  #tokenizing
  preprocess_tokens=word_tokenize(text)

  #stop word| lowering | punctuation| only alpha
  stopwords_list = stopwords.words('english')
  preprocess_tokens = [word.lower() for word in preprocess_tokens if word.lower() not in stop_words]
  preprocess_tokens=[token for token in preprocess_tokens if token.isalpha()]

  # Lemmatization with POS tagging
  lemmatizer = WordNetLemmatizer()
  preprocess_tokens = [lemmatizer.lemmatize(token, get_wordnet_pos(token)) for token in preprocess_tokens]
  return preprocess_tokens

sample_df=pd.read_csv('SMSSpamCollection.csv',sep="\t",names=["label","message"],encoding=encoding)

sample_df["message_preprocess"]=sample_df['message'].apply(lambda x: preprocess_data(x))

In [135]:
sample_df.head()

label                                            message  \
0   ham  Go until jurong point, crazy.. Available only ...   
1   ham                      Ok lar... Joking wif u oni...   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3   ham  U dun say so early hor... U c already then say...   
4   ham  Nah I don't think he goes to usf, he lives aro...   

                                  message_preprocess  
0  [go, jurong, point, crazy, available, bugis, n...  
1                     [ok, lar, joking, wif, u, oni]  
2  [free, entry, wkly, comp, win, fa, cup, final,...  
3      [u, dun, say, early, hor, u, c, already, say]  
4        [nah, think, go, usf, life, around, though]

In [136]:
#create corpus of messages
corpus=df["message_preprocess"].tolist()
corpus[2:5]

[['free',
  'entri',
  'wkli',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkt',
  'may',
  'text',
  'fa',
  'receiv',
  'entri',
  'question',
  'std',
  'txt',
  'rate',
  'c',
  'appli'],
 ['u', 'dun', 'say', 'earli', 'hor', 'u', 'c', 'alreadi', 'say'],
 ['nah', 'think', 'goe', 'usf', 'live', 'around', 'though']]

# Frequency based word Embeddings
 - BOW
 - TFIDF

In [137]:
import numpy as np
from collections import Counter
from math import log

# Corpus
example_corpus = [
    ["This", "movie", "is", "very", "scary", "and", "long"],
    ["This", "movie", "is", "not", "scary", "and", "is", "slow"],
    ["This", "movie", "is", "spooky", "and", "good"]
]

# Function to create Bag-of-Words matrix
def create_bow_matrix(corpus):
    unique_words = set(word for doc in corpus for word in doc)
    word_to_index = {word: i for i, word in enumerate(unique_words)}
    bow_matrix = np.zeros((len(corpus), len(unique_words)))
    for i, doc in enumerate(corpus):
        word_counts = Counter(doc)
        for word, count in word_counts.items():
            bow_matrix[i, word_to_index[word]] = count
    return bow_matrix, list(unique_words)

# Function to create TF-IDF matrix
def create_tfidf_matrix(corpus):
    bow_matrix, unique_words = create_bow_matrix(corpus)
    tfidf_matrix = np.zeros(bow_matrix.shape)
    doc_count = len(corpus)
    for i, doc in enumerate(corpus):
        word_counts = Counter(doc)
        doc_length = sum(word_counts.values())
        for word, count in word_counts.items():
            word_index = unique_words.index(word)
            tf = log(count / doc_length +1)
            idf = log(doc_count / sum(1 for doc in corpus if word in doc))
            tfidf_matrix[i, word_index] = tf * idf
    return tfidf_matrix, unique_words

# Create Bag-of-Words matrix
bow_matrix, bow_feature_names = create_bow_matrix(example_corpus)

# Create TF-IDF matrix
tfidf_matrix, tfidf_feature_names = create_tfidf_matrix(example_corpus)

# Print Bag-of-Words matrix and feature names
print("Bag-of-Words Matrix:")
print(bow_matrix)
print("\nFeature Names:")
print(bow_feature_names)

# Print TF-IDF matrix and feature names
print("\nTF-IDF Matrix:")
print(tfidf_matrix)
print("\nFeature Names:")
print(tfidf_feature_names)

Bag-of-Words Matrix:
[[0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1.]
 [0. 1. 1. 0. 1. 1. 0. 1. 2. 1. 0.]
 [1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0.]]

Feature Names:
['spooky', 'This', 'not', 'very', 'movie', 'and', 'good', 'scary', 'is', 'slow', 'long']

TF-IDF Matrix:
[[0.         0.         0.         0.14669923 0.         0.
  0.         0.05414232 0.         0.         0.14669923]
 [0.         0.         0.12939789 0.         0.         0.
  0.         0.04775691 0.         0.12939789 0.        ]
 [0.16935183 0.         0.         0.         0.         0.
  0.16935183 0.         0.         0.         0.        ]]

Feature Names:
['spooky', 'This', 'not', 'very', 'movie', 'and', 'good', 'scary', 'is', 'slow', 'long']


In [138]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Corpus
example_corpus = [
    "This movie is very scary and long",
    "This movie is not scary and is slow",
    "This movie is spooky and good"
]

# Initialize CountVectorizer for BOW matrix
count_vectorizer = CountVectorizer()

# Fit and transform the corpus into a CountVectorizer BOW matrix
bow_matrix = count_vectorizer.fit_transform(example_corpus)

# Initialize TfidfVectorizer for TF-IDF matrix
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the corpus into a TfidfVectorizer matrix
tfidf_matrix = tfidf_vectorizer.fit_transform(example_corpus)

# Print first few rows of Bag-of-Words matrix and feature names
print("Bag-of-Words Matrix:")
print(bow_matrix.toarray())
print("\nFeature Names:")
print(count_vectorizer.get_feature_names_out())

# Print first few rows of TF-IDF matrix and feature names
print("\nTF-IDF Matrix:")
print(tfidf_matrix.toarray())
print("\nFeature Names:")
print(tfidf_vectorizer.get_feature_names_out())
# Print the shape of each matrix
print("Shape of Bag-of-Words Matrix:", bow_matrix.shape)
print("Shape of TF-IDF Matrix:", tfidf_matrix.shape)

Bag-of-Words Matrix:
[[1 0 1 1 1 0 1 0 0 1 1]
 [1 0 2 0 1 1 1 1 0 1 0]
 [1 1 1 0 1 0 0 0 1 1 0]]

Feature Names:
['and' 'good' 'is' 'long' 'movie' 'not' 'scary' 'slow' 'spooky' 'this'
 'very']

TF-IDF Matrix:
[[0.29628336 0.         0.29628336 0.50165133 0.29628336 0.
  0.38151877 0.         0.         0.29628336 0.50165133]
 [0.26359985 0.         0.5271997  0.         0.26359985 0.44631334
  0.3394328  0.44631334 0.         0.26359985 0.        ]
 [0.32052772 0.54270061 0.32052772 0.         0.32052772 0.
  0.         0.         0.54270061 0.32052772 0.        ]]

Feature Names:
['and' 'good' 'is' 'long' 'movie' 'not' 'scary' 'slow' 'spooky' 'this'
 'very']
Shape of Bag-of-Words Matrix: (3, 11)
Shape of TF-IDF Matrix: (3, 11)


In [139]:
# Create Bag-of-Words matrix
bow_matrix, bow_feature_names = create_bow_matrix(corpus)

# Create TF-IDF matrix
tfidf_matrix, tfidf_feature_names = create_tfidf_matrix(corpus)

# Print Bag-of-Words matrix and feature names
print("Bag-of-Words Matrix:")
print(bow_matrix)
print("\nFeature Names:")
print(bow_feature_names)

# Print TF-IDF matrix and feature names
print("\nTF-IDF Matrix:")
print(tfidf_matrix)
print("\nFeature Names:")
print(tfidf_feature_names)
# Print shape of Bag-of-Words matrix
print("Shape of Bag-of-Words Matrix:", bow_matrix.shape)

# Print shape of TF-IDF matrix
print("Shape of TF-IDF Matrix:", tfidf_matrix.shape)

Bag-of-Words Matrix:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Feature Names:
['ashley', 'texa', 'ca', 'ttyl', 'fraud', 'lara', 'hat', 'honeybe', 'unusu', 'laxinorf', 'pthi', 'role', 'ratio', 'eye', 'hiya', 'lovabl', 'placement', 'persev', 'player', 'cours', 'dey', 'job', 'eightish', 'ab', 'craziest', 'pie', 'shame', 'mess', 'kit', 'credit', 'adrian', 'ben', 'badli', 'okey', 'mall', 'server', 'imag', 'digit', 'slip', 'etc', 'ticket', 'aburo', 'edha', 'spous', 'theme', 'via', 'safeti', 'everywher', 'arrest', 'onlin', 'aathi', 'gibb', 'seat', 'thx', 'dict', 'tomo', 'dippeditinadew', 'eatin', 'xxx', 'mila', 'mmsto', 'unit', 'shhhhh', 'chosen', 'kaypoh', 'loyalti', 'brisk', 'blastin', 'evon', 'lobbi', 'jurong', 'diwali', 'unev', 'umma', 'non', 'sch', 'hard', 'takin', 'dad', 'cm', 'q', 'troubl', 'fluid', 'arabian', 'sundayish', 'tht', 'number', 'goodeven', 'tmrw', 'wonder', 'di

In [140]:
corpus=sample_df["message_preprocess"].tolist()

In [141]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Initialize CountVectorizer for BOW matrix
count_vectorizer = CountVectorizer()

# Fit and transform the corpus into a CountVectorizer BOW matrix
bow_matrix1 = count_vectorizer.fit_transform(corpus)

# Initialize TfidfVectorizer for TF-IDF matrix
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the corpus into a TfidfVectorizer matrix
tfidf_matrix1 = tfidf_vectorizer.fit_transform(corpus)



# Print first few rows of Bag-of-Words matrix and feature names
print("Bag-of-Words Matrix:")
print(bow_matrix1.toarray())
print("\nFeature Names:")
print(count_vectorizer.get_feature_names_out())

# Print first few rows of TF-IDF matrix and feature names
print("\nTF-IDF Matrix:")
print(tfidf_matrix1.toarray())
print("\nFeature Names:")
print(tfidf_vectorizer.get_feature_names_out())
# Print the shape of each matrix
print("Shape of Bag-of-Words Matrix:", bow_matrix.shape)
print("Shape of TF-IDF Matrix:", tfidf_matrix.shape)

AttributeError: 'list' object has no attribute 'lower'